version: '3.8'

services:
    mysqldb:
        container_name: mysql_db
        image: mysql:5.7
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            - MYSQL_DATABASE=$MYSQLDB_NAME
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql/
        networks:
            - backend
    express-api:
        container_name: express_api
        depends_on:
            - mysqldb
        image: express-api:latest
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_NAME
            - DB_PORT=$MYSQLDB_DOCKER_PORT
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        networks:
            - backend
volumes:
    db:

networks:
    backend: