version: '3.8'

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=$MYSQLDB_NAME
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql/
volumes:
    db:
